### ISSUE TITLE
HeaderMap::get_all should not return Option

### ISSUE THREAD

**Issue by joshtriplett** [carllerche/http#111]
Currently, `HeaderMap::get_all` returns an `Option<GetAll<T>>`, with `None` indicating the absence of any header with the specified name. That type signature allows encoding "impossible" situations, which code will then have to handle. Specifically, it allows `Some` of an empty iterator. That's going to force code using this type to have extra logic dismissing that "impossible" case.

Please switch the type to just `GetAll<T>`, with an empty iterator indicating the absence of any header with the specified name. It's still trivial to detect presence/absence of a header (such as via `contains_key`), and this will simplify callers, reducing uses of `.unwrap()` and similar.

**Comment by seanmonstar** [comment]
I suppose this would be a nice, small improvement. Some examples I thought of that would benefit:

```rust
let cookies = req.headers().get_all(SET_COOKIE).map(parse).collect::<Vec<Cookie>>();
```

```rust
for hop in req.headers().get_all(VIA) {
    lol_privacy_track_proxies(hop);
}
```

**Comment by carllerche** [comment]
I think this is probably a good change. I think in the original iteration, `get_all` was actually `get` and it returned `Option` to match `HashMap`. However, since then it was renamed -> `get_all`.

Given that, I think removing the `Option` would be a good change.

**Comment by seanmonstar** [comment]
Looking into this, in order to this, a couple parts of `GetAll` would need to change:

- `key()` currently allows looking up the header name that all the values are related to. If the entry didn't exist, there is no key. This could be changed to return an `Option`, or removed.
- `get()` allows taking a reference to the first header value in this list. If the entry didn't exist, there is no value to return a reference to. This could be changed to return an `Option`, or removed.

I think I lean towards removing both of those methods.

**Comment by joshtriplett** [comment]
@seanmonstar Dropping `GetAll::get()` seems sensible, since `next()` would do the same thing.

I don't think it makes sense for `GetAll::key()` to return an `Option`, so since it can't return the header name you originally looked up, that leaves dropping it entirely.

**Comment by carllerche** [comment]
I'm OK w/ removing those functions.
