### ISSUE TITLE
Use modules vs. not?

### ISSUE THREAD

**Issue by carllerche** [carllerche/http#69]
I have doubts re: #68, which was merged before I could look at it.

Personally, I enjoy the short type names using modules to namespace them. It makes for less imports.

Instead of having to do:

```rust
use http::{RequestBuilder, RequestParts};

fn foo(b: RequestBuilder, p: RequestParts) {
}
```

```rust
use http::request;

fn foo(b: request::Builder, p: request::Parts) {
}
```

Most of the lib is optimized for the module style, so either way it needs to be uniform.

**Comment by theduke** [comment]
+1 for mostly avoiding public names like `Parts` or `Builder`. 

It so often results in awkwardness, you either end up using `use http::request; ... request::Builder` or `use http::request::{Builder as RequestBuilder}` all the time.

**Comment by seanmonstar** [comment]
We had a lot of discussion this morning on this while GitHub was full of unicorns. The outcome was that for these uncommon types, they will just stay as they are in the module. A user should very rarely if ever need to import them, since they are just intermediate types while building requests and responses.

The root level would only have the commonly imported types.

**Comment by carllerche** [comment]
@seanmonstar has summarized the conclusion here.
